description: 'The VSCode app helps to develop all endpoint logic online using the monaco editor.'
screenshot: 'https://raw.githubusercontent.com/apioo/fusio/master/doc/_static/vscode.png'
website: 'https://github.com/apioo/fusio-apps-vscode'