description: 'The VSCode app helps to develop all endpoint logic online using the monaco editor.'
screenshot: 'https://www.fusio-project.org/media/apps/vscode.png'
website: 'https://github.com/apioo/fusio-apps-vscode'